### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by nbari** [epazote/scheduler#1]
Improve the `README.md` with a better explanation, and example would be nice.

**Comment by CS-5** [comment]
Any more specifics?

**Comment by nbari** [comment]
probably this could help: https://github.com/epazote/epazote/blob/master/start.go#L57

The idea is to have better docs even is a very basic package

**Comment by CS-5** [comment]
Just a basic README explaining what it does and how to use it?

**Comment by nbari** [comment]
yes that would be helpful

**Comment by CS-5** [comment]
Alrighty, I'll get on that. Will submit a pull-request whenever October 1st rolls around, as to fall within the Hacktoberfest guidelines.

**Comment by ch3ck** [comment]
Hi @nbari How do you add the Hacktoberfest label to your GitHub issue? I will like to create such on one of my projects.

**Comment by CS-5** [comment]
Is this application intended to be used in conjunction with another? I am not extremely familiar with the Go language, however I know enough that you need to have a main package to initiate the program run. Is there something I am missing?

**Comment by CS-5** [comment]
If anyone else who feels they are more capable would like to work on this issue as well, feel free. I may not be able to address full documentation due to certain time constraints.

**Comment by nbari** [comment]
@Ch3ck within your project, click on issues (https://github.com/epazote/scheduler/issues) next on labels and add a new one.

**Comment by nbari** [comment]
@avesanen many thanks
